### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ligi** [Shard-Labs/remix-sourcify#16]
when trying to get this mainnet contract: https://contractrepostaging.komputing.org/contract/mainnet/0x00B948381e5b84E04024bA6c07Edf9F0B135deE4/

![Selection_431](https://user-images.githubusercontent.com/111600/80272426-748a7180-86c9-11ea-89dc-ddd5f10888df.png)

**Comment by edisinovcic** [comment]
This errors should no longer be visible. @ligi can you confirm this?

**Comment by edisinovcic** [comment]
Fixed, closing this.
